name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Get latest version
        id: qemu-version
        run: |
            pip3 install -U lastversion
            QEMU_VERSION=$(lastversion qemu)
            echo "Latest QEMU version is $QEMU_VERSION"
            echo "tag=v${QEMU_VERSION}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with: 
          tag: ${{ steps.qemu-version.outputs.tag }}
          repo: 'cocoa-xu/qemu-build'
      
      - name: Update if tag not exists
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.qemu-version.outputs.tag }}
          git push origin ${{ steps.qemu-version.outputs.tag }}
